### ISSUE TITLE
In-memory serialization?

### ISSUE THREAD

**Issue by wlandau** [qsbase/qs2#4]
`qs` had `qserialize()`, and I noticed `qs2` does not yet have an equivalent function for in-memory serialization. Is this part of your plan for `qs2`? If so, it would really help me reduce the memory footprint of `targets`, c.f. https://github.com/ropensci/targets/discussions/1352#discussioncomment-11053363.

**Comment by traversc** [comment]
Yup, will do!

**Comment by traversc** [comment]
Added in memory serialization for both R and C/C++ with the latest commit. Still needs unit tests and documentation but seems to be working right.

R Example:
```
x <- rnorm(1e6)
xs <- qs_serialize(x, nthreads=4)
y <- qs_deserialize(xs)
identical(x,y)
```

C++ example:
```
// [[Rcpp::depends(qs2)]]
#include <Rcpp.h>
#include "qs2_external.h"
using namespace Rcpp;

// [[Rcpp::export]]
SEXP test_qs_serialize(SEXP x) {
  uint64_t len = 0;
  char * buffer = c_qs_serialize(x, &len, 10, 4); // object, buffer length, compress_level, nthreads
  SEXP y = c_qs_deserialize(buffer, len, 4);      // buffer, buffer length, nthreads
  free(buffer);                                   // must manually free buffer
  return y;
}

/*** R
x <- runif(1e7)
stopifnot(test_qs_serialize(x) == x)
*/
```

**Comment by wlandau** [comment]
That's fantastic, thank you so much!

**Comment by traversc** [comment]
Keeping this issue open until I push to CRAN
