### ISSUE TITLE
Reading/saving qs format in python

### ISSUE THREAD

**Issue by elgabbas** [qsbase/qs2#6]
Hello,

I have a question rather than an issue. I started using qs recently and it was a perfect option for me to speed up reading/saving large R objects, thanks.

Currently, I am moving back and forth between R and python for my current project: saving rds files in R and reading/processing them in python, then saving the output as rds files. However, it is really time-consuming to read and write rds files, especially if I need to process too many files, some of them are very large (6GB). Is it possible to read/write qs files directly in python?

Another point, I just noticed today that qs2 may replace qs at some time. Will the new qs2 package be able to read files saved by qs? I save files as `.qs` format. Is it the right time to move from qs to qs2 or qs2 is still under development?

Tanks

**Comment by traversc** [comment]
Currently it is not possible. I plan for some interchange with the qdata format in the future, but it will take some time. 

Yes, please switch to qs2. The qs2 package will not be able to read qs1 files.

**Comment by elgabbas** [comment]
That's clear. Thanks @traversc for your reply and for developing this nice package. All the best.
