### ISSUE TITLE
Inconsistent problem with saving/loading float32 objects as `qs2` files

### ISSUE THREAD

**Issue by elgabbas** [qsbase/qs2#7]
Hello,

I am having trouble saving and loading a float32 matrix object as `qs2` file. 

Here is an [example of problematic data](https://github.com/user-attachments/files/18050010/object.zip).

```
require(qs2)
require(float)
# Loading example data 
load("object.Rdata")
```
```
str(object)
# Formal class 'float32' [package "float"] with 1 slot
# ..@ Data: int [1:16988, 1:25] 9.15e-06 3.07e-06 5.60e-05 1.71e-04 4.32e-05 ...
```

```
# saving and loading data
qs2::qs_save(object, "object.qs2")    # no warnings or errors
qs2::qs_read(file = "object.qs2") 
# Error in qs2::qs_read(file = "object.qs2") : Decompression error
# Warning message:
#   In qs2::qs_read(file = "object.qs2") : File read interrupted
```
```
# This works without issue
qs2::qs_save(as.double(object), "object.qs2")
qs2::qs_read(file = "object.qs2")

# This also works
qs::qsave(object, "object.qs")
qs::qread(file = "object.qs")
```
----

Nevertheless, it seems that this problem is not per saving/loading float32 data per se, as many other objects of the same class work. Here is an [example data](https://github.com/user-attachments/files/18050031/object2.zip) of the same dimension.
```
str(object2)
# Formal class 'float32' [package "float"] with 1 slot
# ..@ Data: int [1:16988, 1:25] 2.69e-14 3.71e-15 2.40e-13 8.25e-14 4.82e-14 4.69e-14 ...
qs2::qs_save(object2, "object2.qs2")
qs2::qs_read(file = "object2.qs2")                                          # This works
```
Any explanation for this?

Thanks in advance

**Comment by traversc** [comment]
Thanks for the report, I was able to reproduce it and fix it. Could you test out the latest commit?

`remotes::install_github("qsbase/qs2")`

**Comment by elgabbas** [comment]
Thanks a lot @traversc. This solved the issue.

**Comment by traversc** [comment]
Great! Keeping this issue open until CRAN update.
